const menu = [
  {
    name: "tea",
    category: "tea",
    price: 347984.0,
    poor: true,
    refills: false,
    img: "tea!.jpg",
  },

  {
    name: "tea but better",
    category: "tea",
    price: 3479842.0,
    poor: false,
    refills: true,
    img: "tea but better.jpg",
  },
  {
    name: "flowers",
    category: "decorative",
    price: 5000.0,
    poor: true,
    refills: true,
    img: "flowers.jpg",
  },
  {
    name: "strawberry tea sandwich",
    category: "edibles",
    price: 3438904.0,
    poor: false,
    refills: false,
    img: "strawberry.jpg",
  },
  {
    name: "cucumber tea sandwich",
    category: "edibles",
    price: 3438904.0,
    poor: false,
    refills: false,
    img: "cucumber.jpg",
  },
  {
    name: "vanilla cream scones",
    category: "edibles",
    price: 3438904.0,
    poor: false,
    refills: false,
    img: "scones.jpg",
  },
  {
    name: "coconut chiffon cake slice",
    category: "edibles",
    price: 63843.0,
    poor: true,
    refills: false,
    img: "coconut.jpg",
  },
  {
    name: "whipped cream",
    category: "side",
    price: 433.0,
    poor: true,
    refills: true,
    img: "whipped cream.jpg",
  },
  {
    name: "clotted cream",
    category: "side",
    price: 433.0,
    poor: true,
    refills: false,
    img: "clotted.jpg",
  },
  {
    name: "strawberry jam",
    category: "side",
    price: 433.0,
    poor: true,
    refills: false,
    img: "jam.jpg",
  },
];

export { menu };
